import { NextRequest, NextResponse } from 'next/server'
import { vapiConfig } from '@/lib/vapi-config'

/**
 * Vapi Webhook Handler
 * Receives all server-side events from Vapi.ai during live phone calls
 * 
 * Event flow:
 * 1. assistant-request → Return dynamic assistant config
 * 2. transcript → Process customer speech through pipeline
 * 3. function-call → Execute tools (CRM lookup, etc.)
 * 4. end-of-call-report → Persist call data
 * 5. hang → Clean up session
 */
export async function POST(req: NextRequest) {
    try {
        const body = await req.json()
        const { message } = body

        console.log('[Vapi Webhook] Received event:', message.type, 'Call ID:', body.call?.id)

        // Route to appropriate handler based on event type
        switch (message.type) {
            case vapiConfig.webhookEvents.ASSISTANT_REQUEST:
                return handleAssistantRequest(body)

            case vapiConfig.webhookEvents.TRANSCRIPT:
                return handleTranscript(body)

            case vapiConfig.webhookEvents.SPEECH_UPDATE:
                return handleSpeechUpdate(body)

            case vapiConfig.webhookEvents.FUNCTION_CALL:
                return handleFunctionCall(body)

            case vapiConfig.webhookEvents.END_OF_CALL_REPORT:
                return handleEndOfCall(body)

            case vapiConfig.webhookEvents.HANG:
                return handleHang(body)

            case vapiConfig.webhookEvents.STATUS_UPDATE:
                return handleStatusUpdate(body)

            default:
                console.warn('[Vapi Webhook] Unknown event type:', message.type)
                return NextResponse.json({})
        }
    } catch (error) {
        console.error('[Vapi Webhook] Error processing webhook:', error)
        return NextResponse.json(
            { error: 'Internal server error' },
            { status: 500 }
        )
    }
}

/**
 * Handle assistant-request event
 * Vapi calls this to get or modify assistant configuration dynamically
 * Must respond within 7.5 seconds
 */
async function handleAssistantRequest(body: any) {
    const { call } = body

    console.log('[Vapi Webhook] Assistant request for call:', call.id)

    // Return minimal assistant config
    // In production, this would be generated by PromptBuilder based on CLIENT.md
    const assistantConfig = {
        firstMessage: vapiConfig.assistantConfig.firstMessage,
        model: vapiConfig.assistantConfig.model,
        voice: vapiConfig.assistantConfig.voice,
        silenceTimeoutSeconds: vapiConfig.assistantConfig.silenceTimeoutSeconds,
        maxDurationSeconds: vapiConfig.assistantConfig.maxDurationSeconds,
    }

    return NextResponse.json({
        assistant: assistantConfig,
    })
}

/**
 * Handle transcript event
 * Processes final transcripts through the Mastra pipeline
 */
async function handleTranscript(body: any) {
    const { message, call } = body
    const transcript = message.transcript

    console.log('[Vapi Webhook] Transcript:', {
        callId: call.id,
        role: message.role,
        text: transcript,
    })

    // TODO: Route to VapiSessionBridge → VoiceSessionManager → WorkflowController
    // For now, just log

    return NextResponse.json({})
}

/**
 * Handle speech-update event
 * Real-time partial transcripts (informational only)
 */
async function handleSpeechUpdate(body: any) {
    const { message } = body

    console.log('[Vapi Webhook] Speech update:', {
        role: message.role,
        text: message.transcript,
        status: message.status,
    })

    return NextResponse.json({})
}

/**
 * Handle function-call event
 * Vapi assistant wants to execute a tool/function
 */
async function handleFunctionCall(body: any) {
    const { message, call } = body
    const functionCall = message.functionCall

    console.log('[Vapi Webhook] Function call:', {
        callId: call.id,
        name: functionCall.name,
        parameters: functionCall.parameters,
    })

    // TODO: Route to internal tool handlers
    // Example: CRM lookup, CLIENT.md generation, etc.

    // For now, return mock result
    const result = {
        result: 'Function executed successfully',
    }

    return NextResponse.json(result)
}

/**
 * Handle end-of-call-report event
 * Call analytics and final data persistence
 */
async function handleEndOfCall(body: any) {
    const { message, call } = body

    console.log('[Vapi Webhook] End of call report:', {
        callId: call.id,
        duration: message.endedReason,
        costs: message.cost,
    })

    // TODO: Persist CLIENT.md, update deal health, log analytics

    return NextResponse.json({})
}

/**
 * Handle hang event
 * Call disconnected
 */
async function handleHang(body: any) {
    const { call } = body

    console.log('[Vapi Webhook] Call hung up:', call.id)

    // TODO: Clean up session via VoiceSessionManager.stopSession()

    return NextResponse.json({})
}

/**
 * Handle status-update event
 * Call status changes (ringing, in-progress, etc.)
 */
async function handleStatusUpdate(body: any) {
    const { message, call } = body

    console.log('[Vapi Webhook] Status update:', {
        callId: call.id,
        status: message.status,
    })

    return NextResponse.json({})
}
